version: '3.3'
services:
  face-api:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
 ####   depends_on:
 ####     - db


 ####   db:
 ####     image: postgres:alpine
 ####     restart: always
 ####     environment:
 ####       POSTGRES_USER: root
  ####      POSTGRES_PASSWORD: root
 ####       POSTGRES_DB: face_recognition
  ####    ports:
  ####      - 5552:5432
  ####    volumes:
   ####     - postgres_face_api_data:/var/lib/postgresql/data/


volumes:
  postgres_face_api_data:
